# Generated by Django 5.1.6 on 2025-03-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_deviceenergyusage_userenergyusage_delete_energyusage'),
        ('users', '0011_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityevent',
            name='joined',
        ),
        migrations.AddField(
            model_name='communityevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_events', to='users.owner'),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
