# Generated by Django 5.1.6 on 2025-03-16 12:53

import devicesharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicesharing', '0003_alter_listing_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateTimeField(default=devicesharing.models.default_due_date),
        ),
    ]
