# Generated by Django 5.1.6 on 2025-03-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicesharing', '0004_request_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_requested',
            field=models.BooleanField(default=False),
        ),
    ]
