# Generated by Django 5.1.6 on 2025-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_guest_allowed_rooms_guest_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='verfied',
            field=models.BigIntegerField(default=0),
        ),
    ]
