# Generated by Django 5.1.6 on 2025-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_guest_verfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='verfied',
        ),
        migrations.AddField(
            model_name='guest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
