# Generated by Django 5.1.6 on 2025-03-16 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_monitorfixeddevice_monitorvariabledevice_and_more'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='house_id',
        ),
        migrations.AddField(
            model_name='automation',
            name='end_time',
            field=models.TimeField(default='00:01'),
        ),
        migrations.AddField(
            model_name='automation',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='devices.house'),
        ),
        migrations.AddField(
            model_name='automation',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
