# Generated by Django 5.1.6 on 2025-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_remove_automation_house_id_automation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automation',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
